apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
{{ include "ritchie-server.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{ range $i, $var := .Values.service.ports -}}
  - name: {{ $var.name }}
    port: {{ $var.port }}
    targetPort: {{ $var.target_port }}
  {{ end }}
  selector:
    app.kubernetes.io/name: {{ include "ritchie-server.name" . }}
---