# The configurations that used for the recording, feel free to edit them
config:

  # Specify a command to be executed
  # like `/bin/bash -l`, `ls`, or any other commands
  # the default is bash for Linux
  # or powershell.exe for Windows
  command: bash -l

  # Specify the current working directory path
  # the default is the current working directory path
  cwd: /demo

  # Export additional ENV variables
  env:
    recording: true

  # Explicitly set the number of columns
  # or use `auto` to take the current
  # number of columns of your shell
  cols: 150

  # Explicitly set the number of rows
  # or use `auto` to take the current
  # number of rows of your shell
  rows: 25

  # Amount of times to repeat GIF
  # If value is -1, play once
  # If value is 0, loop indefinitely
  # If value is a positive number, loop n times
  repeat: 0

  # Quality
  # 1 - 100
  quality: 100

  # Delay between frames in ms
  # If the value is `auto` use the actual recording delays
  frameDelay: auto

  # Maximum delay between frames in ms
  # Ignored if the `frameDelay` isn't set to `auto`
  # Set to `auto` to prevent limiting the max idle time
  maxIdleTime: 2000

  # The surrounding frame box
  # The `type` can be null, window, floating, or solid`
  # To hide the title use the value null
  # Don't forget to add a backgroundColor style with a null as type
  frameBox:
    type: floating
    title: Ritchie Cli
    style:
      border: 0px black solid
      # boxShadow: none
      # margin: 0px

  # Add a watermark image to the rendered gif
  # You need to specify an absolute path for
  # the image on your machine or a URL, and you can also
  # add your own CSS styles
  watermark:
    imagePath: null
    style:
      position: absolute
      right: 15px
      bottom: 15px
      width: 100px
      opacity: 0.9

  # Cursor style can be one of
  # `block`, `underline`, or `bar`
  cursorStyle: block

  # Font family
  # You can use any font that is installed on your machine
  # in CSS-like syntax
  fontFamily: "Monaco, Lucida Console, Ubuntu Mono, Monospace"

  # The size of the font
  fontSize: 14

  # The height of lines
  lineHeight: 1

  # The spacing between letters
  letterSpacing: 0

  # Theme
  theme:
    background: "transparent"
    foreground: "#afafaf"
    cursor: "#c7c7c7"
    black: "#232628"
    red: "#fc4384"
    green: "#b3e33b"
    yellow: "#ffa727"
    blue: "#75dff2"
    magenta: "#ae89fe"
    cyan: "#708387"
    white: "#d5d5d0"
    brightBlack: "#626566"
    brightRed: "#ff7fac"
    brightGreen: "#c8ed71"
    brightYellow: "#ebdf86"
    brightBlue: "#75dff2"
    brightMagenta: "#ae89fe"
    brightCyan: "#b1c6ca"
    brightWhite: "#f9f9f4"

# Records, feel free to edit them
records:
  - delay: 381
    content: "\e]0;ritchie@zup:/demo\a\e]7;file://zup-1338/demo\a\e]0;ritchie@zup: /demo\a\e[01;32mritchie@zup\e[00m:\e[01;34m/demo\e[00m$ "
  - delay: 1505
    content: r
  - delay: 167
    content: i
  - delay: 68
    content: t
  - delay: 176
    content: ' '
  - delay: 207
    content: a
  - delay: 233
    content: w
  - delay: 249
    content: s
  - delay: 312
    content: ' '
  - delay: 1129
    content: u
  - delay: 96
    content: p
  - delay: 188
    content: d
  - delay: 32
    content: a
  - delay: 184
    content: t
  - delay: 112
    content: e
  - delay: 116
    content: ' '
  - delay: 317
    content: k
  - delay: 207
    content: u
  - delay: 157
    content: b
  - delay: 132
    content: e
  - delay: 381
    content: c
  - delay: 140
    content: o
  - delay: 31
    content: 'n'
  - delay: 104
    content: f
  - delay: 120
    content: i
  - delay: 128
    content: g
  - delay: 1437
    content: "\r\n"
  - delay: 44
    content: "\e[1mFormula running on env: \e[36mDefault\e[0m\r\n\e[0m\r\n\e[0G\e[2K\e[1;92m? \e[0m\e[1;99mPick the region: \e[0m  \e[36m[Use arrows to move, type to filter, ? for more help]\e[0m\r\n\e[1;36m> sa-east-1\e[0m\r\n\e[39m  us-east-2\e[0m\r\n\e[39m  us-east-1\e[0m\r\n\e[39m  us-west-1\e[0m\r\n\e[39m  us-west-2\e[0m\r\n\e[39m  af-south-1\e[0m\r\n\e[39m  ap-east-1\e[0m\r\n\e[?25l"
  - delay: 1614
    content: "\e[?25h\e[0G\e[2K\e[1F\e[2K\e[1F\e[2K\e[1F\e[2K\e[1F\e[2K\e[1F\e[2K\e[1F\e[2K\e[1F\e[2K\e[1F\e[2K\e[1;92m? \e[0m\e[1;99mPick the region: \e[0m\e[36m sa-east-1\e[0m\r\n\e[0G\e[2K\e[1;92m? \e[0m\e[1;99mCluster Name:  \e[0m\e[36m[? for help]\e[0m \e[?25l\e7\e[999;999f\e[6n"
  - delay: 10
    content: "\e8\e[?25h\e[6n"
  - delay: 4181
    content: ritchie-test-cluster
  - delay: 2911
    content: "\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1E\e[1F\e[0G\e[2K\e[1;92m? \e[0m\e[1;99mCluster Name:  \e[0m\e[36mritchie-test-cluster\e[0m\r\nRunning: aws eks --region sa-east-1 update-kubeconfig --name ritchie-test-cluster ...\r\n"
  - delay: 6306
    content: "Updated context arn:aws:eks:sa-east-1:01234567890:cluster/ritchie-test-cluster in /home/ritchie/.kube/config\r\n"
  - delay: 69
    content: "\e]0;ritchie@zup:/demo\a\e]7;file://zup-1338/demo\a\e]0;ritchie@zup: /demo\a\e[01;32mritchie@zup\e[00m:\e[01;34m/demo\e[00m$ "
  - delay: 69
    content: "\r\n"
  - delay: 10000
    content: "sair\r\n"
