# SH
BINARY_NAME=coffee-python
DIST=../dist
DIST_MAC_DIR=$(DIST)/darwin/bin
DIST_LINUX_DIR=$(DIST)/linux/bin
DIST_WIN_DIR=$(DIST)/windows/bin

build:
	mkdir -p $(DIST_MAC_DIR) $(DIST_LINUX_DIR) $(DIST_WIN_DIR)
	cp coffee.py $(DIST)/coffee.py
	chmod +x $(DIST)/coffee.py