envVars:
  - name: GIT_REPO_URL
    value: "https://api.github.com/repos/ZupIT/ritchie-formulas"
  - name: TREE_FILE
    value: "/tree/tree.json"
  - name: GIT_TOKEN
    value: "becd4b7a621d95328bcdc2b4f82dbc2bd1a1d7c7"
  - name: POOLING_TIME
    value: "10"
  - name: VAULT_ADDR
    value: "http://vault-cli:8200"
  - name: VAULT_AUTHENTICATION
    value: "KUBERNETES"
  - name: VAULT_K8S_ROLE
    value: "ritchie_credential_role"


replicaCount: 1

image:
  repository: ritchie-server
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name:

podSecurityContext: {}

securityContext: {}

resources: 
  limits:
    cpu: 512m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  enabled: true
  failureThreshold: 3
  httpGet:
    path: /health
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

service:
  name: ritchie-server
  type: NodePort
  ports:
  - name: http
    port: 3000
    target_port: 3000

ingress:
  enabled: true
  externalPort: 3000
  hosts:
    - name: ritchie-api.hostname-placeholder
      path: /
      annotations: 
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/subnets: aws-subnets-placeholder
        alb.ingress.kubernetes.io/certificate-arn: certificate-arn-placeholder
        external-dns.alpha.kubernetes.io/hostname:  ritchie.hostname-placeholder


ritchie:
  orgs:
    - name: zup
      keycloak:
        url: "https://ritchie-keycloak.itiaws.dev"
        realm: "ritchie"
        clientId: "user-login"
        clientSecret: "71da7105-477b-4854-ae6c-1263abf7ea50"
      repositories: |

        [
          {
            "name": "commons",
            "priority": 0,
            "treePath": "https://ritchie-cli-bucket234376412767550.s3-sa-east-1.amazonaws.com/tree/tree.json"
          },
          {
            "name": "zup",
            "priority": 1,
            "treePath": "https://ritchie-cli-bucket234376412767550.s3-sa-east-1.amazonaws.com/tree/tree-zup.json"
          }
        ]

      cliVersionPath:
        provider: "s3"
        url: "http://ritchie-cli-bucket152849730126474.s3-website-sa-east-1.amazonaws.com/stable.txt"
      oauth :
        url: "https://ritchie-keycloak.itiaws.dev/auth/realms/ritchie"
        clientId: "oauth"
      credentials: |

        {
          "github": [
            {
              "field": "username",
              "type": "text"
            },
            {
              "field": "token",
              "type": "password"
            }
          ],
          "gitlab": [
            {
              "field": "username",
              "type": "text"
            },
            {
              "field": "token",
              "type": "password"
            }
          ],
          "aws": [
            {
              "field": "accessKeyId",
              "type": "text"
            },
            {
              "field": "secretAccessKey",
              "type": "password"
            }
          ],
          "darwin": [
            {
              "field": "username",
              "type": "text"
            },
            {
              "field": "password",
              "type": "password"
            }
          ],
          "jenkins": [
            {
              "field": "username",
              "type": "text"
            },
            {
              "field": "token",
              "type": "password"
            }
          ],
          "email-zup": [
            {
              "field": "email",
              "type": "text"
            },
            {
              "field": "token",
              "type": "password"
            }
          ],
          "kubeconfig": [
            {
                "field": "base64config",
                "type" : "text"
            }
          ]
        }

    - name: itau
      keycloak:
        url: "https://ritchie-keycloak.itiaws.dev"
        realm: "ritchie"
        clientId: "user-login"
        clientSecret: "71da7105-477b-4854-ae6c-1263abf7ea50"
      repositories: |

        [
          {
            "name": "commons",
            "priority": 0,
            "treePath": "https://ritchie-cli-bucket234376412767550.s3-sa-east-1.amazonaws.com/tree/tree.json"
          },
          {
            "name": "zup",
            "priority": 1,
            "treePath": "https://ritchie-cli-bucket234376412767550.s3-sa-east-1.amazonaws.com/tree/tree-zup.json"
          }
        ]

      cliVersionPath:
        provider: "s3"
        url: "http://ritchie-cli-bucket152849730126474.s3-website-sa-east-1.amazonaws.com/stable.txt"
      oauth :
        url: "https://ritchie-keycloak.itiaws.dev/auth/realms/ritchie"
        clientId: "oauth"
      credentials: |

        {
          "github": [
            {
              "field": "username",
              "type": "text"
            },
            {
              "field": "token",
              "type": "password"
            }
          ]
        }



imageCredentials:
  registry: 648839423626.dkr.ecr.sa-east-1.amazonaws.com

