# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '${project_name}' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Beagle'
  pod 'Beagle/Preview'
  pod 'YogaKit', :git => 'https://github.com/ZupIT/YogaKit'

  # Pods for test

end
