name: Pre-Commit

on: 
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
      - name: Install Pre-Commit
        run: pip install pre-commit
      - name: Run Pre-Commit
        run: pre-commit run --all-files
                    