# SH
BINARY_NAME=coffee-shell
DIST=../dist
DIST_MAC_DIR=$(DIST)/darwin/bin
DIST_LINUX_DIR=$(DIST)/linux/bin
DIST_WIN_DIR=$(DIST)/windows/bin
build:
	mkdir -p $(DIST_MAC_DIR) $(DIST_LINUX_DIR) $(DIST_WIN_DIR)
	cp main.sh $(DIST)/coffee.sh
	chmod +x $(DIST)/coffee.sh